### ISSUE TITLE
能够打繁体出简体吗

### ISSUE THREAD

**Issue by jiongge** [GuiWonder/TCFontCreator#1]
能够打繁体出简体吗？一个字库有简繁两种字体，能把繁体对应位置换成字库对应的简体吗？

**Comment by GuiWonder** [comment]
可以试一下[小合简化体](https://github.com/GuiWonder/XiaoheSimplifyFonts)。

**Comment by GuiWonder** [comment]
[小合简化体](https://github.com/GuiWonder/XiaoheSimplifyFonts)的转换脚本应该可以通用，以后会考虑加入打繁体出简体的功能。

**Comment by GuiWonder** [comment]
新版已加入打繁体出简体功能。

**Comment by jiongge** [comment]
试了下，完美实现，3q
