### ISSUE TITLE
可否使用本人的舊字形異體字轉換字庫

### ISSUE THREAD

**Issue by haydenwong7bm** [GuiWonder/TCFontCreator#10]
本人的舊字形異體字轉換字庫包含更多異體字轉換，包括「為–爲」，「娱–娛」，使用我的轉換字庫可使此處理工具作爲舊字形轉換字體轉換。可參考[我的repo](https://github.com/haydenwong7bm/inherited-glyphs-converter/blob/main/conversion-tables/variants_list.txt)。

**Comment by GuiWonder** [comment]
感謝提供優質轉換字庫。由於字庫中包含很多一般字型不收錄的生僻字，因此考慮了一下暫時先不使用了。
