### ISSUE TITLE
一简对多繁的问题

### ISSUE THREAD

**Issue by jiongge** [GuiWonder/TCFontCreator#2]
还有个问题就是如果我简体转繁体的时候选择一对多处理方式为第三个：一简对多繁的话，生成的字库里会把我自定义的字体给删除了，比如我在UF000加了个字，生成后就没了

**Comment by GuiWonder** [comment]
一简对多繁需要使用伪字图作为简繁转换的词汇，而一个字体的字图数目是有限制的，所以需要从字体中删除一些生僻字的字图。详细说明位于 [Ayaka](https://github.com/ayaka14732) 的[《正确实现简转繁字体》](https://ayaka.shn.hk/s2tfont/)一文。一简对多繁字体会损失掉一部分字图。一简多繁字体使用词汇来自[OpenCC](https://github.com/BYVoid/OpenCC)，词汇量较大。繁转简字体使用的词汇量较少，没有删除字图。

**Comment by jiongge** [comment]
OpenType 字体的局限性
在上述方法中，一条简繁词语的对应关系需要使用一个伪字图，而伪字图也会占据字图数量。OpenType 字体的字图数量上限为 65535 个。
为了防止字图数量超过上限，可以采取两种方法：
第一：可以从字体中删除一些生僻字的字图。
第二：可以适当删除一些简繁词语的对应关系。应优先删除繁简同形、且在逐字转换时不会产生错误的词语，例如上面例子中的「播出」。

我也是才看到，可以关了。
还有个问题就是如果一对多处理方式选择不处理的话，算法是不是字库里的简体字如果没有一对多繁体就把这个简体unicode改到繁体上，如果有一对多这个简体字unicode保持不变是么？而且他的所有繁体字也会生成是么？？？

**Comment by GuiWonder** [comment]
嗯，不处理简繁一对多，只把简繁一对一的汉字简体Unicode映射到繁体字图上，一简多繁的汉字没有处理。
