### ISSUE TITLE
可否將標點也一起轉換？

### ISSUE THREAD

**Issue by ChellyL** [GuiWonder/TCFontCreator#3]
如題，在簡繁體中的引號不同，簡體用“”、‘’，繁體用「」和『』，能不能在轉換字體同時也將部分標點也一并轉換？
以及簡體中標點靠左，繁體標點居中，能否也在轉換時實現標點位置的改變？

**Comment by GuiWonder** [comment]
改變標點位置需要重繪字圖，本工具無法完成。本工具原本是帶有引號的轉換，後來失效了，現已修復，非常感謝您的反饋。

**Comment by ChellyL** [comment]
感谢告知~
