### ISSUE TITLE
转换入简得繁后字体缺“袴”字

### ISSUE THREAD

**Issue by ChellyL** [GuiWonder/TCFontCreator#4]
如题，尝试用工具转换了入简得繁的一点明朝，阅读时发现转换后的字体缺“袴”字，原字体有这个字，请问这类情况提issue会补上吗？

**Comment by GuiWonder** [comment]
您可能使用的一简多繁字体功能，一简多繁字体的制作方法来自 [Ayaka](https://github.com/ayaka14732) 的[《正确实现简转繁字体》](https://ayaka.shn.hk/s2tfont/)，此方法使用伪字图作为简繁转换的词汇，字体的字图数量上限为 65535，为了防止字图数量超过上限，需要从字体中删除一些生僻字的字图。详细说明位于 [《正确实现简转繁字体》](https://ayaka.shn.hk/s2tfont/)。
程序默认保留的汉字位于 datas/Hans.txt 文件，如果有需要可以修改一下。

**Comment by ChellyL** [comment]
明白原理了o(*￣▽￣*)ブ，感谢回复~
