### ISSUE TITLE
簡轉繁一對多功能有問題

### ISSUE THREAD

**Issue by tonyhuan** [GuiWonder/TCFontCreator#5]
生成簡轉繁字體、異體字選擇[台灣]時，[使用單一常用字]的一對多處理方式沒有效果，跟[不處理一對多]做出的結果差不多，此功能在舊版本是可以正常執行的。若異體字選擇香港，則可以正常轉換。

另外，在[使用詞彙正確一簡對多繁]的功能中，所有異體字選項都只在單字有效，詞彙選字部分無效會有異體字，因為詞彙對照表只有一個。

**Comment by GuiWonder** [comment]
您好，我測試了一下「單一常用字」功能，但似乎併未發現問題。
![NoTitle](https://github.com/GuiWonder/TCFontCreator/assets/55447192/44d045b6-6e5b-4a1f-94ae-e9c65933161c)

詞彙問題會在下一版更正，感謝反饋。

**Comment by GuiWonder** [comment]
新版已匹配詞彙中的異體字。
