### ISSUE TITLE
转换失败

### ISSUE THREAD

**Issue by zhuzhe537** [GuiWonder/TCFontCreator#6]
提示typeerror: ord()expected a character,but string of length 2 found

**Comment by GuiWonder** [comment]
这个错误很可能是**字典**中有多余字符或其他不规范内容引起的。我暂时还没遇到这个错误，所以还查不到原因。如果你的字典修改过，可尝试一下使用默认字典。谢谢反馈！

**Comment by zhuzhe537** [comment]
> 这个错误很可能是**字典**中有多余字符或其他不规范内容引起的。我暂时还没遇到这个错误，所以还查不到原因。如果你的字典修改过，可尝试一下使用默认字典。谢谢反馈！

谢谢！的确是替换字典出错了。
另外转换后的字体缩略图“简体/繁体”有时会变成同偏旁乱码生僻字，不知是什么原因。

**Comment by GuiWonder** [comment]
缩略图问题我也不清楚什么原因。
