### ISSUE TITLE
日文字体转旧字体报 not applicable

### ISSUE THREAD

**Issue by kchr1n** [GuiWonder/TCFontCreator#7]
使用工具进行日本字体新字体转旧字体时会报 Runtime Error: This font is not applicable。
确有提示「仅部分字体」，想请教一下，如何判断我载入的字体 applicable 与否呢？
我载入的字体是 Fontworks 的「筑紫ゴシック Pr5N R」，理应是符合「日本字体」的要求的。

**Comment by GuiWonder** [comment]
您好，此工具只对部分日本字体有效。判断字体是否可用，没有什么好方法，用工具转换一下提示 Runtime Error: This font is not applicable 就说明字体不适用。

**Comment by kchr1n** [comment]
谢谢回复。
不过 Morisawa 的 UD 新ゴ 可以正常转换，尽管判断是否可用的手段不是很明确，但非常感激作者开发工具，省了手动调字形位置的时间，谢谢！
