### ISSUE TITLE
未能更新詞庫

### ISSUE THREAD

**Issue by lsmrachel** [GuiWonder/TCFontCreator#9]
STPhrases共48697行, 在網上搜尋了一個範圍更廣的詞庫共155486行。嘗試運行EXE時出現錯誤: 
<img width="304" alt="Screenshot 2024-08-06 231038" src="https://github.com/user-attachments/assets/9bfa6931-f4b2-44b4-b618-08c717b84d33">
請問能否處理? 謝謝!

**Comment by GuiWonder** [comment]
抱歉，這個無法處理。此簡轉繁方案要求字體字形總數和詞彙總數相加不能超過 65535 個。[技術來源](https://ayaka.shn.hk/s2tfont/hant/)

**Comment by lsmrachel** [comment]
明白，謝謝！
